### PR TITLE
bump base64 dependency to 0.8

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Looks like base64 0.8 doesn't compile on the older rustc included in travis; is bumping the minimum version ok?

**Comment by jcreekmore** [comment]
Bumping it is fine. Why don’t you include a patch to bump the minimum version to 1.20?

--
Jonathan Creekmore
jonathan@thecreekmores.org

**Comment by alex** [comment]
👍  thanks!

**Comment by cardoe** [comment]
If you nudge up the minimum libstd then bump up the middle version for semver. 

--
Doug

**Pull request merged**
