### PR TITLE
fix text

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by cardoe** [comment]
There's no commit message reason how this fixes a test. This just looks like one of those attempts to get an account where you can claim you've contributed to X many repos.

**Review by cardoe — CHANGES_REQUESTED** [review]
There's no commit message reason how this fixes a test. This just looks like one of those attempts to get an account where you can claim you've contributed to X many repos.

**Comment by tshepang** [comment]
did not leave reason as I thought the fix was obvious, like I would have said "typo"

**Comment by tshepang** [comment]
@jcreekmore what would a better fix for the typo be

**Pull request closed without merging**
