### PR TITLE
downgrade msrv to 1.60.0

### PR DESCRIPTION
**Pull request by koushiro**
result: https://github.com/koushiro/pem-rs/pull/1

### CODE REVIEW

**Comment by cardoe** [comment]
Why?

**Comment by koushiro** [comment]
> Why?

why not? the crate don't use any new features of 1.60.0+

**Comment by cardoe** [comment]
It’s up to every maintainer in the Rust community to set their own MSRV. There’s no uniform policy or recommendation (I do feel there should be).

Setting on a newer version means that it will be easier to take other depends and updates in the future without a breaking bump.

While I don’t own this crate I don’t think you’ve expressed a reasonable why.

**Comment by koushiro** [comment]
> Setting on a newer version means that it will be easier to take other depends and updates in the future without a breaking bump.

If this crate has many dependencies, it might make sense to me. But this crate only have base64 and optional serde dependencies.

**Pull request merged**
